/**
 * KERNEL TRAIL: Quantum Pass, the three terminal commands. Curriculum map,
 * "Leg 3. QUANTUM PASS", "Terminal commands introduced", byte for byte:
 * WP-15 ships the same definitions, so registering these is a no-op, and a
 * definition that differed would throw at registration (scope correction
 * section 3). The handlers are WP-15's; a leg supplies none.
 */
import type { TerminalCommandDef } from '@game/types';

export const terminalCommands: readonly TerminalCommandDef[] = [
  {
    name: 'sched',
    usage: 'sched [--policy <id>] [--quantum <n>] [--aging <n>] [--levels <n,n,n>]',
    summary: 'Read or set the CPU scheduling policy and its parameters.',
    manual: [
      'sched with no arguments prints the current policy, its parameters, and the live',
      'metrics. With arguments it changes the policy immediately, on the running system.',
      '',
      'Policies:',
      '  fcfs            run to completion in arrival order. Simple and fair in the weakest',
      '                  sense of fair. One long job at the front makes everyone behind it',
      '                  wait for all of it. That is the convoy effect and it is why this',
      '                  policy is a teaching example rather than a choice.',
      '  sjf             pick the shortest next burst. Provably gives the minimum average',
      '                  waiting time for a fixed set of jobs. Requires knowing burst',
      '                  lengths in advance, which no real system does; see --estimate.',
      '  srtf            preemptive sjf. A shorter arrival preempts the running job.',
      '                  Better average waiting time, more switches, and long jobs can be',
      '                  pushed back indefinitely.',
      '  priority        pick the lowest priority number. Nothing guarantees a high number',
      '                  ever runs. This policy starves processes. It is not a defect in',
      '                  the implementation.',
      '  priority_aging  the same, plus every process gains a priority level for each',
      '                  --aging ticks it spends ready without running. Starvation becomes',
      '                  impossible because waiting is itself a path to the front.',
      '  rr              each ready process gets --quantum ticks in turn. Response time is',
      '                  bounded by (n-1) * quantum, which is the property interactive',
      '                  work needs. Average waiting time is worse than sjf.',
      '  mlfq            several round-robin queues at different levels. A process that',
      '                  uses its whole quantum drops a level; a process that blocks early',
      '                  stays. This separates interactive work from CPU-bound work',
      '                  without being told which is which.',
      '',
      'On --quantum. There is a floor and a ceiling and both hurt. Set it near 1 and the',
      'system spends its time saving and restoring registers; measure it with top and watch',
      'sys climb while throughput falls. Set it far above the typical burst and round robin',
      'degenerates into fcfs, because everyone finishes before being preempted. The useful',
      'range is a small multiple of the typical burst: long enough that most bursts finish',
      'inside one slice, short enough that response time stays bounded.',
      '',
      'On --aging. Zero disables it. Any nonzero value makes starvation impossible under',
      'priority, at the cost of letting low-priority work eventually displace high-priority',
      'work. That trade is the point.',
      '',
      'See also: gantt, nice, top, codex scheduling_criteria.',
    ].join('\n'),
    chapter: { chapter: 5, title: 'CPU Scheduling', sections: ['5.3.1', '5.3.2', '5.3.3', '5.3.4', '5.3.6'] },
  },
  {
    name: 'nice',
    usage: 'nice [-n <delta>] <pid>',
    summary: 'Adjust one process priority number.',
    manual: [
      'nice changes the priority of a running process by the given delta.',
      '',
      'The number is a priority, and in this system, as in Silberschatz, a lower number',
      'means more urgent. nice -n -5 makes a process more likely to run. nice -n 5 makes it',
      'less likely. The name comes from being nice to other processes by lowering your own',
      'claim, which is why the sign reads backwards from what most people expect the first',
      'time.',
      '',
      'nice is a blunt instrument and it is worth knowing what it cannot do. It does not',
      'give a process more processor time in absolute terms; it changes its position in a',
      'comparison against other ready processes. Under fcfs it has no effect at all, because',
      'fcfs never consults priority. Under round robin it has no effect either. It matters',
      'under priority, priority_aging and mlfq.',
      '',
      'Using nice to rescue a starving process works, once. It fixes this process now. It',
      'does not fix the policy that starved it, and the next process down will starve in',
      'exactly the same way. Aging fixes the policy.',
      '',
      'See also: sched --aging, ps -l, codex starvation.',
    ].join('\n'),
    chapter: { chapter: 5, title: 'CPU Scheduling', sections: ['5.3.4'] },
  },
  {
    name: 'gantt',
    usage: 'gantt [--last <ticks>] [--replay <policy>] [--metrics]',
    summary: 'Draw the execution timeline, and replay the same arrivals under another policy.',
    manual: [
      'gantt draws which process held the processor during each tick, as a chart. Gaps are',
      'context switches and idle time, drawn to scale, so overhead is visible as area rather',
      'than quoted as a number.',
      '',
      '--metrics prints the four numbers that decide whether a policy is doing well:',
      '  waiting time     total time ready but not running. Minimise this for throughput.',
      '  turnaround time  arrival to completion. Waiting time plus service time.',
      '  response time    arrival to first run. Minimise this for anything a human waits on.',
      '  cpu utilisation  fraction of ticks doing work rather than switching or idling.',
      'These conflict. A policy that minimises response time will switch often and lose',
      'utilisation to overhead. Deciding which number matters is the scheduling problem;',
      'the algorithms are just answers to different versions of it.',
      '',
      '--replay re-runs the exact arrival times and burst lengths you already experienced,',
      'under a different policy, and prints both charts. The run is deterministic, so this',
      'is a real comparison rather than an estimate. It is the only honest way to answer',
      'the question "would something else have been better", and you can ask it after the',
      'fact, which is when the question usually occurs to people.',
      '',
      '  gantt --replay sjf      what the last segment looked like under sjf',
      '',
      'See also: sched, top, codex scheduling_criteria.',
    ].join('\n'),
    chapter: { chapter: 5, title: 'CPU Scheduling', sections: ['5.2', '5.8.1', '5.8.2'] },
  },
];
