/**
 * KERNEL TRAIL, the Narrows: the three commands this leg adds.
 *
 * Transcribed from `docs/05-CURRICULUM-MAP.md`, "Leg 4. THE NARROWS",
 * "Terminal commands introduced", byte for byte and extracted from the
 * document rather than retyped. WP-15 shipped every one of these definitions,
 * so re-shipping them registers nothing new and throws nothing; a definition
 * that differed by one character would throw naming the first differing line,
 * which is what makes this transcription checkable rather than decorative.
 */
import type { TerminalCommandDef } from '@game/types';

export const terminalCommands: readonly TerminalCommandDef[] = [
  {
    name: 'lock',
    usage: 'lock [--list] [--mark <start> <end>] [--inherit on|off] [--kind mutex|semaphore|monitor]',
    summary: 'List synchronisation primitives, mark a critical section, and set inheritance.',
    manual: [
      'lock --list prints every synchronisation primitive: its kind, its value, who holds',
      'it, and who is queued on it.',
      '',
      'A critical section is a region of code that touches shared data and must not be',
      'interleaved with another region touching the same data. Marking one is a claim you',
      'are making about your own code, and the system takes you at your word. Nothing in',
      'the hardware associates a lock with the data it protects. The association exists',
      'only in the discipline of the code, which is why two crossings guarding the same',
      'ledger with two different mutexes will still corrupt it, and why both crossings will',
      'look correct in isolation.',
      '',
      'Three requirements any correct solution must satisfy at once:',
      '  mutual exclusion  at most one process inside the section at a time',
      '  progress          if the section is free, some waiting process gets in, and the',
      '                    decision is not deferred forever by processes not trying to',
      '                    enter',
      '  bounded waiting   there is a limit on how many times others can enter ahead of',
      '                    you. Without this you have mutual exclusion and starvation.',
      'A protocol missing any one of them fails, and it usually fails on the third, quietly,',
      'under load.',
      '',
      'On section length. A section that is too long excludes everyone for no reason and',
      'converts a parallel program into a serial one; you measured that effect on the',
      'weave. A section that is too short leaves a write outside the guard, which is the',
      'defect you are here to avoid. Mark the smallest region that contains every access to',
      'the shared data, and no more.',
      '',
      '--inherit on enables priority inheritance: while a low-priority holder blocks a',
      'high-priority waiter, the holder temporarily runs at the waiter priority. This costs',
      'nothing when there is no contention and it is the difference between a bounded wait',
      'and an unbounded one.',
      '',
      'See also: race, trace, sem, codex critical_section.',
    ].join('\n'),
    chapter: { chapter: 6, title: 'Synchronization Tools', sections: ['6.2', '6.5', '6.8'] },
  },
  {
    name: 'race',
    usage: 'race [--list] [--show <n>] [--expected]',
    summary: 'List detected data races and show the interleaving that caused each.',
    manual: [
      'race lists every data race the system detected, with the participating processes,',
      'the value that resulted, and the value that should have resulted.',
      '',
      '--show expands one race into its instruction interleaving. This is the part worth',
      'reading slowly. A statement like count = count + 1 is one line of source and three',
      'machine operations: load count into a register, add one, store the register back.',
      'Between any two of those operations the scheduler may preempt you, because the',
      'scheduler has no idea that those three operations were meant to be one thing.',
      '',
      'So two processes each running count = count + 1 can interleave as: A loads 5, B',
      'loads 5, A adds and stores 6, B adds and stores 6. Two increments, one result. No',
      'instruction executed incorrectly. The defect is entirely in the interleaving.',
      '',
      'This is why "the operation is fast, so it will not be interrupted" is not an',
      'argument, and why "I checked and it works" is not evidence. A race that needs a',
      'specific interleaving to appear will not appear on most runs, and will appear on the',
      'run that matters.',
      '',
      'See also: trace --replay, lock, codex race_condition.',
    ].join('\n'),
    chapter: { chapter: 6, title: 'Synchronization Tools', sections: ['6.1', '6.2'] },
  },
  {
    name: 'trace',
    usage: 'trace [--from <tick>] [--to <tick>] [--pid <pid>] [--replay <n>]',
    summary: 'Print the kernel event log for a tick range, and replay a recorded interleaving.',
    manual: [
      'trace prints the raw event log: every state change, every acquisition, every',
      'preemption, in order, with tick numbers.',
      '',
      'This run is deterministic. The whole run is a function of its seed and the decisions',
      'you have made, which means an interleaving that happened once can be reproduced',
      'exactly, forever. --replay takes a recorded race and re-runs the identical sequence',
      'of scheduling decisions against whatever protocol you have now installed.',
      '',
      'That property is why this game can teach synchronisation and a real machine mostly',
      'cannot. On a real machine you fix a race, the race stops appearing, and you have no',
      'way to know whether you fixed it or got lucky. Here you can fix it and prove it,',
      'against the exact interleaving that broke it.',
      '',
      '  trace --pid 4 --from 200 --to 260   everything Program 4 did in that window',
      '  trace --replay 1                    re-run recorded race 1 under current locking',
      '',
      'See also: race, gantt --replay, lock.',
    ].join('\n'),
    chapter: { chapter: 6, title: 'Synchronization Tools', sections: ['6.1'] },
  },
];
