import {it,expect} from 'vitest';
import {Scene,Group,Vector2,Vector3,Quaternion,Mesh,BoxGeometry} from 'three/webgpu';
import {FocusCameraRig,computeLockedPose,focusPath,arcLift,type FocusTarget} from '../../src/render/camera/FocusCamera';
import {BlendedPerspectiveCamera} from '../../src/render/camera/projection';
import {TravelCamera} from '../../src/render/camera/TravelCamera';
import {EASE,cubicBezier} from '../../src/design/motion';
import {getMaterial,materialFocusUniform,disposeMaterials} from '../../src/render/materials';
function setup(){const scene=new Scene(),camera=new BlendedPerspectiveCamera(46,1,.1,2000);camera.position.set(0,5,15);camera.lookAt(0,0,0);camera.updateMatrixWorld();const rig=new FocusCameraRig({scene,camera,aspect:1,viewportHeightPx:900});const anchor=new Group();scene.add(anchor);const target:FocusTarget={id:'target',anchor,planeNormal:new Vector3(0,0,1),planeUp:new Vector3(0,1,0),extents:new Vector2(4,4),padding:.12,focusSet:[],dimOthers:.82,labelPlane:'billboard-to-focus',minGlyphHeight:.1};rig.register(target);return {scene,camera,rig,anchor,target};}
it('four modes, precise durations, release strength falls continuously and unknown id is inert',()=>{
 const {rig}=setup();expect(rig.engage('unknown')).toBe(false);rig.engage('target');rig.update(.519);expect(rig.state.mode).toBe('engaging');rig.update(.001);expect(rig.state.mode).toBe('locked');rig.release();expect(rig.state.blend).toBe(1);rig.update(.19);expect(rig.state.blend).toBeGreaterThan(0);expect(rig.state.blend).toBeLessThan(1);rig.release();rig.update(.19);expect(rig.state.mode).toBe('free');expect(rig.state.blend).toBe(0);rig.dispose();
});
it('padded limiting dimension fills .78 for twenty combinations',()=>{const {target}=setup();for(let i=1;i<=20;i++){target.extents.set(i,21-i);const aspect=.5+i/10,pose=computeLockedPose(target,aspect,46*Math.PI/180);expect(Math.max(target.extents.y,target.extents.x/aspect)*1.12/pose.orthoHeight).toBeCloseTo(.78,12);}});
it('easing endpoints, monotonic named curves and general CSS solver property',()=>{
 for(const curve of [EASE.focusIn,EASE.focusOut]){expect(curve(0)).toBe(0);expect(curve(1)).toBe(1);let previous=0;for(let i=0;i<=1000;i++){const v=curve(i/1000);expect(v).toBeGreaterThanOrEqual(previous);previous=v;}}
 const reference=(x:number,a:number,b:number,c:number,d:number)=>{const calc=(t:number,p:number,q:number)=>3*(1-t)**2*t*p+3*(1-t)*t*t*q+t**3;let lo=0,hi=1;for(let i=0;i<80;i++){const t=(lo+hi)/2;if(calc(t,a,c)<x)lo=t;else hi=t;}return calc((lo+hi)/2,b,d);};
 for(const c of [[.16,.84,.24,1],[.4,0,.2,1],[.2,0,0,1],[.65,0,.35,1],[0,0,0,1],[1,0,1,1]] as const){const fn=cubicBezier(c[0],c[1],c[2],c[3]);for(let i=0;i<=1000;i++)expect(Math.abs(fn(i/1000)-reference(i/1000,c[0],c[1],c[2],c[3]))).toBeLessThan(1e-6);}
 expect(cubicBezier(0,0,0,1)(.001)).toBeCloseTo(.028,12);
});
it('leading rotation, printed arc and lift equations, constant FOV',()=>{const {rig,camera,target}=setup();rig.engage('target');rig.update(.52/1.12);expect(camera.quaternion.angleTo(rig.state.to.quaternion)).toBeLessThan(1e-6);expect(camera.position.distanceTo(rig.state.to.position)).toBeGreaterThan(0);expect(camera.fov).toBe(46);
 const from={position:new Vector3(0,0,10),quaternion:new Quaternion(),fov:1,orthoHeight:1},to=computeLockedPose(target,1,1),out=new Vector3();for(const top of [0,2,4,8,16])expect(arcLift(from,to,top)).toBe(Math.max(2,top-Math.min(from.position.y,to.position.y))*.35);focusPath(from,to,5,.5,out);expect(out.distanceTo(from.position.clone().lerp(to.position,.5))).toBeGreaterThan(from.position.distanceTo(to.position)*.1);rig.dispose();});
it('subtree focus, moving anchors, zoom bounds and readable sub-regions',()=>{const {rig,target,anchor,camera}=setup();const a=new Group(),b=new Group(),c=new Group();anchor.add(a);a.add(b);b.add(c);rig.setLabelGlyphHeight(target.id,.01);rig.engage(target.id);rig.update(.52);expect(rig.focusWeight(c)).toBe(1);expect(rig.focusWeight(new Group())).toBeCloseTo(.18);const height=rig.state.to.orthoHeight;expect(height).toBeLessThan(computeLockedPose(target,1,46*Math.PI/180).orthoHeight);rig.zoom(100);rig.update(0);expect(2/camera.projectionMatrix.elements[5]!).toBeCloseTo(height*1.6);rig.pan(100,100);rig.update(0);const before=camera.position.x;anchor.position.x=10;rig.update(0);expect(camera.position.x-before).toBeCloseTo(10);rig.zoom(.0001);rig.update(0);expect(2/camera.projectionMatrix.elements[5]!).toBeCloseTo(height*.6);rig.dispose();});
it('release reaches moving tracker; repeated state reads reuse a record',()=>{const {rig,camera}=setup();const focus=new Vector3();rig.setFreeTarget({focus,yawRad:0,pitchRad:0,distanceM:10});rig.update(0);rig.engage('target');rig.update(.52);focus.x=20;rig.setFreeTarget({focus,yawRad:0,pitchRad:0,distanceM:10});for(let i=0;i<500;i++)rig.update(.01);rig.release();rig.update(.38);expect(camera.position.x).toBeCloseTo(20,6);expect(rig.state).toBe(rig.state);rig.dispose();});
it('interruptions preserve the exact initial matrix and focus amount',()=>{const {rig,camera}=setup();rig.engage('target');rig.update(.1);const matrix=camera.projectionMatrix.clone(),weight=rig.state.blend;rig.release();rig.update(0);expect(camera.projectionMatrix.equals(matrix)).toBe(true);expect(rig.state.blend).toBe(weight);rig.unregister('target');rig.update(.38);expect(rig.state.mode).toBe('free');rig.dispose();});
it('travel rejects locked rotation, clamps adversarial input and spring does not overshoot',()=>{const scene=new Scene(),travel=new TravelCamera(scene,1,900);travel.orbit(0,100);travel.dolly(1e6);travel.update(0);expect(travel.camera.position.length()).toBeCloseTo(90);travel.track(new Vector3(10,0,0));let previous=travel.camera.position.x;for(let i=0;i<500;i++){travel.update(.01);expect(travel.camera.position.x).toBeGreaterThanOrEqual(previous-1e-12);expect(travel.camera.position.x).toBeLessThanOrEqual(10+1e-12);previous=travel.camera.position.x;}travel.dispose();});
it('400 objects sharing three materials are partitioned with at most one uniform write each frame',()=>{
 const {rig,scene,anchor}=setup(),geometry=new BoxGeometry();const bases=[getMaterial('void-surface','ready','low'),getMaterial('emissive-panel','page_clean','low'),getMaterial('emissive-line','running','low')];
 for(let i=0;i<400;i++){const mesh=new Mesh(geometry,bases[i%3]!);(i<200?anchor:scene).add(mesh);}
 rig.engage('target');const counts=new Map<object,number>();scene.traverse(o=>{if('material' in o){const u=materialFocusUniform((o as Mesh).material as typeof bases[number]);if(u&&!counts.has(u)){let value=u.value;counts.set(u,0);Object.defineProperty(u,'value',{get:()=>value,set:(v:number)=>{value=v;counts.set(u,counts.get(u)!+1);}});}}});
 rig.update(.1);for(const writes of counts.values())expect(writes).toBe(1);expect(counts.size).toBe(6);rig.dispose();geometry.dispose();disposeMaterials();
});

it('moving parent lift is world-space and viewport changes preserve release start',()=>{
 const {rig,anchor,scene,camera}=setup();const parent=new Group();scene.remove(anchor);parent.position.y=20;parent.add(anchor);scene.add(parent);rig.engage('target');expect(rig.state.to.position.y).toBe(20);rig.update(.52);rig.release();rig.update(.1);const projection=camera.projectionMatrix.clone(),position=camera.position.clone();rig.setViewport(2,1200);rig.update(0);expect(camera.projectionMatrix.equals(projection)).toBe(true);expect(camera.position.distanceTo(position)).toBeLessThan(1e-12);rig.update(.28);expect(rig.state.mode).toBe('free');rig.dispose();
});
it('travel rotation is refused under focus lock',()=>{const {target}=setup(),scene=new Scene(),travel=new TravelCamera(scene,1,900);scene.add(target.anchor);travel.update(0);travel.focus.register(target);travel.focus.engage(target.id);travel.update(.52);const q=travel.camera.quaternion.clone();expect(travel.orbit(1,1)).toBe(false);travel.update(0);expect(travel.camera.quaternion.angleTo(q)).toBeLessThan(1e-6);travel.dispose();});
it('camera frame path including engaged and locked updates allocates no named math objects',()=>{
 const {rig}=setup();rig.engage('target');rig.update(0);const counts:Record<string,number>={};Object.assign(globalThis,{__ktAlloc:(name:string)=>{counts[name]=(counts[name]??0)+1;}});try{for(let i=0;i<300;i++)rig.update(.01);expect(counts).toEqual({});}finally{Object.assign(globalThis,{__ktAlloc:undefined});rig.dispose();}
});
