import {it,expect} from 'vitest';
import {BoxGeometry,Matrix4,Vector3,Quaternion,Color} from 'three/webgpu';
import {ManagedBatch} from '../../src/render/RendererBackend';
import {getMaterial,disposeMaterials} from '../../src/render/materials';
import {InstancedBatch} from '../../src/world/instancing/InstancedBatch';
import {SlotAllocator} from '../../src/world/instancing/SlotAllocator';
import {assertCeiling} from '../../src/world/instancing/assertCeiling';
import {PROFILES} from '../../src/platform';
import {LAYER} from '../../src/design';
function setup(capacity=400){const geometry=new BoxGeometry(),material=getMaterial('emissive-panel','page_clean','high');const handle=new ManagedBatch({name:'kt.structures.test.batch',capacity,geometry:'slab',material:'structure',perInstanceColour:true,castShadow:false,layer:LAYER.STRUCTURES},geometry,material,()=>{});return {handle,batch:new InstancedBatch(handle),dispose(){handle.dispose();geometry.dispose();disposeMaterials();}};}
it('twelve floats, three coalesced ranges, matrix unchanged unless moved',()=>{const {batch,handle,dispose}=setup(4);const slot=batch.allocate(),matrix=new Matrix4();batch.move(slot,matrix);handle.flush();const version=handle.object.instanceMatrix.version;const data={colorGain:[.1,.2,.3,1] as const,statePhase:[2,.5,3,.18] as const,patternId:[.6,.2,4,9] as const};batch.write(slot,data);batch.write(slot,data);handle.flush();expect(Array.from(handle.colorGain.slice(0,4))).toEqual(Array.from(new Float32Array(data.colorGain)));for(const name of ['aColorGain','aStatePhase','aPatternId'])expect(handle.object.geometry.getAttribute(name)).toHaveProperty('updateRanges',[{start:0,count:4}]);expect(handle.object.instanceMatrix.version).toBe(version);expect(batch.move(slot,matrix)).toBe(false);batch.release(slot);expect(handle.count).toBe(0);dispose();});
it('lowest-free reuse and high-water over 1000 operations',()=>{const slots=new SlotAllocator(32),live=new Set<number>();let seed=42;for(let i=0;i<1000;i++){seed=(seed*1664525+1013904223)>>>0;if(live.size===32||(live.size&&seed%2)){const slot=[...live][seed%live.size]!;live.delete(slot);slots.free(slot);}else{let next=0;while(live.has(next))next++;expect(slots.allocate()).toBe(next);live.add(next);}expect(slots.highWater).toBe(live.size?Math.max(...live)+1:0);expect(slots.count).toBe(live.size);}});
it('ceilings throw in dev; static beam clamp uses maxInstances',()=>{for(const profile of Object.values(PROFILES)){expect(()=>assertCeiling('beams',profile.maxInstances.beams+1,profile,true)).toThrow('ceiling');expect(assertCeiling('beams',profile.maxInstances.beams+1,profile,false)).toBe(profile.maxInstances.beams);const geometry=new BoxGeometry(),handle=new ManagedBatch({name:'beam',capacity:512,geometry:'beam',material:'beam',perInstanceColour:true,castShadow:false,layer:LAYER.BEAMS},geometry,getMaterial('volumetric-beam','running',profile.tier),()=>{});handle.clamp(profile);handle.count=512;expect(handle.count).toBe(profile.maxInstances.beams);handle.dispose();geometry.dispose();}disposeMaterials();});
it('400 live instances over 300 frames allocate none of four instrumented constructors',()=>{const {batch,handle,dispose}=setup(),matrix=new Matrix4();for(let i=0;i<400;i++){const slot=batch.allocate();matrix.makeTranslation(i,0,0);batch.move(slot,matrix);}handle.flush();const data={colorGain:[.1,.2,.3,1] as const,statePhase:[0,0,1,1] as const,patternId:[1,0,0,0] as const};const counts:Record<string,number>={Matrix4:0,Vector3:0,Color:0,Quaternion:0};Object.assign(globalThis,{__ktAlloc:(name:string)=>{counts[name]=(counts[name]??0)+1;}});try{new Matrix4();new Vector3();new Color();new Quaternion();expect(counts).toEqual({Matrix4:1,Vector3:1,Color:1,Quaternion:1});for(const name of Object.keys(counts))counts[name]=0;for(let frame=0;frame<300;frame++){for(let slot=0;slot<400;slot++)batch.write(slot,data);handle.flush();}expect(counts).toEqual({Matrix4:0,Vector3:0,Color:0,Quaternion:0});}finally{Object.assign(globalThis,{__ktAlloc:undefined});dispose();}});
