/**
 * KERNEL TRAIL: the Allocation Yards' four instruments, transcribed from
 * `docs/05-CURRICULUM-MAP.md`, "Leg 7. THE ALLOCATION YARDS", byte for byte.
 *
 * WP-15 already shipped every one of these definitions, so re-shipping them
 * identically registers nothing new and throws nothing (scope correction
 * section 3). They are declared here because `Leg.terminalCommands` is what
 * the host hands to `Shell.registerAll`, and because a leg that named them
 * without carrying them could not be read on its own.
 *
 * Do not reword, reflow or add a section. `manuals.test.ts` asserts every
 * line against the curriculum map.
 */
import type { TerminalCommandDef } from '@game/types';

export const terminalCommands: readonly TerminalCommandDef[] = [
  {
    name: 'free',
    usage: 'free [-f] [-h]',
    summary: 'Report memory totals, and with -f the shape of the free space.',
    manual: [
      'free prints total, used and free memory.',
      '',
      '-f prints something the totals cannot tell you: the shape of the free space. It',
      'lists every free run with its size, and the largest single run.',
      '',
      'That last number is the one that decides whether an allocation succeeds under',
      'contiguous allocation. A request for 12 contiguous frames fails when the largest',
      'free run is 9, regardless of whether 200 frames are free in total. The memory exists',
      'and it is unusable, because it is in the wrong shape. That is external',
      'fragmentation, and it is why an out-of-memory failure with plenty of free memory is',
      'a normal event rather than a contradiction.',
      '',
      'Two failures look identical in the totals and need opposite responses:',
      '  no_space       genuinely not enough free memory. Compaction will not help. You',
      '                 need to free something or run fewer things.',
      '  fragmentation  enough free memory, wrong shape. Compaction will help, at the cost',
      '                 of moving every occupied run and stalling every process that owns',
      '                 one. Paging avoids the problem entirely instead of curing it.',
      'Read the reason on the failure event before you spend anything.',
      '',
      'See also: frag, pagetable, vmstat, codex fragmentation.',
    ].join('\n'),
    chapter: { chapter: 9, title: 'Main Memory', sections: ['9.2.3'] },
  },
  {
    name: 'pagetable',
    usage: 'pagetable [pid] [--entry <page>] [--translate <logical>] [--bits]',
    summary: 'Show a process page table and translate logical addresses through it.',
    manual: [
      'pagetable prints one row per page of a process address space.',
      '',
      'Paging splits the address space into fixed-size pages and physical memory into',
      'frames of the same size, and keeps a table mapping one to the other. The mapping is',
      'arbitrary, so a process address space can be contiguous while the memory holding it',
      'is scattered anywhere. That is the whole trick, and it is why paging makes external',
      'fragmentation impossible: any free frame fits any page.',
      '',
      'What it does not remove is internal fragmentation. A process needing 2.3 pages gets',
      '3, and 0.7 of a page is wasted inside the last frame. Average waste is half a page',
      'per process, which is why page size is a real decision: larger pages mean smaller',
      'page tables and more internal waste.',
      '',
      'A logical address splits into a page number and an offset. The page number indexes',
      'this table to find a frame number; the offset is carried across unchanged. With a',
      '256-byte page, logical address 1000 is page 3, offset 232. If page 3 maps to frame',
      '11, the physical address is 11 * 256 + 232.',
      '',
      '--bits shows the per-page protection bits. These are enforced by the memory',
      'management unit on every access, not by any code you write, which is the only reason',
      'they are worth anything. A page marked non-executable cannot be executed even by the',
      'process that owns it and wants to.',
      '',
      'Note the cost this table implies. Every memory access now needs a table lookup',
      'first, which is itself a memory access. Without help, paging doubles the cost of',
      'every access. See tlb.',
      '',
      'See also: tlb, free, frag, codex paging.',
    ].join('\n'),
    chapter: { chapter: 9, title: 'Main Memory', sections: ['9.3.1', '9.3.2', '9.3.3', '9.4.1'] },
  },
  {
    name: 'tlb',
    usage: 'tlb [--stats] [--entries <n>] [--flush]',
    summary: 'Report translation lookaside buffer hit rate and size.',
    manual: [
      'tlb reports hits, misses, hit rate, and the number of entries.',
      '',
      'The translation lookaside buffer is a small associative cache of recent page-to-frame',
      'mappings, sitting in the memory management unit. It exists because paging otherwise',
      'costs two memory accesses per access: one to read the page table, one to read the',
      'data. The TLB makes the first one free when it hits.',
      '',
      'Effective access time = h * m + (1 - h) * 2m, where h is the hit rate and m is one',
      'memory access. At h = 0.99 you pay 1.01m and paging is nearly free. At h = 0.5 you',
      'pay 1.5m and half your memory bandwidth is going to translation.',
      '',
      'The hit rate is not a property of the hardware. It is a property of your access',
      'pattern. A TLB with 16 entries covers 16 pages; a loop touching 8 pages hits',
      'constantly and a loop striding across 400 pages misses constantly, on the same',
      'hardware. Buying more entries helps a little and costs real money. Improving',
      'locality helps a lot and costs a route choice.',
      '',
      '--flush empties the TLB, which is what happens on every context switch unless the',
      'entries are tagged with an address space id. That is a hidden cost of switching, on',
      'top of the register save you already measured.',
      '',
      'See also: pagetable, top, codex tlb.',
    ].join('\n'),
    chapter: { chapter: 9, title: 'Main Memory', sections: ['9.3.2'] },
  },
  {
    name: 'frag',
    usage: 'frag [--internal] [--external] [--compare] [--compact]',
    summary: 'Measure fragmentation, compare allocation strategies, and compact.',
    manual: [
      'frag reports internal and external fragmentation separately, because they are',
      'different problems with opposite cures.',
      '',
      '  external  free memory exists but is split into runs too small to use. Caused by',
      '            variable-size contiguous allocation over time. Cured by compaction, or',
      '            avoided by paging.',
      '  internal  memory was allocated in fixed units larger than the request, and the',
      '            remainder inside the unit is unusable. Caused by fixed-size allocation.',
      '            Cured by smaller units, which cost more table space.',
      'Moving from contiguous allocation to paging trades the first for the second. That is',
      'a good trade, and it is a trade rather than a solution.',
      '',
      '--compare replays the recorded allocation sequence under all four strategies and',
      'prints the resulting fragmentation for each. On most sequences first fit and best fit',
      'land close together, with first fit faster; worst fit does badly, despite the',
      'plausible argument that leaving the largest hole must leave the most useful hole. It',
      'leaves the most holes, which is the opposite of useful. Run it before you believe any',
      'of this.',
      '',
      '--compact slides every occupied run together. It works, and it stops every process',
      'that owns memory for the duration, and it must update every base register. Price it',
      'against the alternative before spending.',
      '',
      'See also: free -f, pagetable, codex fragmentation.',
    ].join('\n'),
    chapter: { chapter: 9, title: 'Main Memory', sections: ['9.2.2', '9.2.3', '9.3.1'] },
  },
];
