/** KERNEL TRAIL: the Allocation Yards' event deck, narrative bible 8, leg 7. Weights sum to 100. */
import type { RandomEventDef } from '@game/types';

export const eventTable: readonly RandomEventDef[] = [
  {
    id: 'yards.no_fit',
    weight: 14,
    title: 'No Fit',
    narration: 'The request is for eleven contiguous frames. There are ninety free and the largest run is seven.',
    targets: null, inflicts: 'fragmented',
    resourceDelta: {},
    onlyIf: null,
  },
  {
    id: 'yards.best_fit_slivers',
    weight: 12,
    title: 'Slivers',
    narration: 'Best fit has been running here for a long time and every allocation left the smallest possible remainder. The yard is full of holes two frames wide.',
    targets: 'cartographer', inflicts: 'fragmented',
    resourceDelta: { quota: -40 },
    onlyIf: null,
  },
  {
    id: 'yards.buddy_split_tax',
    weight: 11,
    title: 'Rounded Up',
    narration: 'A request for nine frames is served from a sixteen-frame block because that is the smallest power of two that holds it. Seven frames are allocated to nothing.',
    targets: null, inflicts: null,
    resourceDelta: { quota: -55 },
    onlyIf: null,
  },
  {
    id: 'yards.page_table_walk',
    weight: 12,
    title: 'Four-Level Walk',
    narration: 'Every address the convoy resolves takes four memory accesses to translate before it takes one to use. The translation cache is cold and the yard is large.',
    targets: null, inflicts: null,
    resourceDelta: { cycles: -55 },
    onlyIf: null,
  },
  {
    id: 'yards.tlb_reach',
    weight: 16,
    title: 'Warm Translation Cache',
    narration: 'The convoy\'s working set fits inside the translation cache for the width of the yard. Hit rate holds at ninety-six percent and the walk cost disappears.',
    targets: null, inflicts: null,
    resourceDelta: { cycles: 65 },
    onlyIf: null,
  },
  {
    id: 'yards.compaction_crew',
    weight: 13,
    title: 'Compaction Pass',
    narration: 'A maintenance pass slides every allocation toward the low end of the yard and leaves one run of free space behind it. It takes a long time and it is worth all of it.',
    targets: null, inflicts: null,
    resourceDelta: { quota: 95, cycles: -20 },
    onlyIf: null,
  },
  {
    id: 'yards.slab_yard',
    weight: 12,
    title: 'Slab Yard',
    narration: 'A slab allocator here hands out fixed-size objects from pre-carved caches, so nothing it serves fragments anything. The convoy takes what it can carry.',
    targets: null, inflicts: null,
    resourceDelta: { blocks: 24, quota: 35 },
    onlyIf: null,
  },
  {
    id: 'yards.free_run_found',
    weight: 10,
    title: 'Contiguous Run',
    narration: 'A departing workload releases sixty-four adjacent frames in one operation. VESPER redraws the map before the free list has finished coalescing.',
    targets: 'cartographer', inflicts: null,
    resourceDelta: { quota: 80 },
    onlyIf: null,
  },
];
